"""
File:
    Product Detection

Purpose:
    This script detects products  within each masked shelf image generated by the
    get_masked_images module. By processing each shelf individually instead of
    the entire store image, the model focuses exclusively on the shelf contents,
    reducing background distractions and improving product detection accuracy.

Input:
    - A directory of masked shelf images generated by get_masked_images.
    - Each image represents a single detected shelf region.

Output:
    - A directory containing one JSON file for each masked shelf image.
    - Each JSON file includes:
        - Detected products
        - Product categories
        - Bounding boxes
        - Confidence scores
        - Category-wise product counts

Main Functionality:
    - Reads each masked shelf image.
    - Sends the image to the Gemini model together with a structured prompt.
    - Detects every visible product instance on the shelf.
    - Estimates a product name, generic category, bounding box, and confidence
      for each detected product.
    - Produces a category summary containing the number of detected products
      per category.
    - Saves the structured detection results as JSON files.

Workflow:
    detect_shelves
            ↓
    get_masked_images
            ↓
    Masked shelf images
            ↓
    Product detection (this script)
            ↓
    Product annotations (JSON)

Model:
    - Google Gemini 3.5 Flash Lite
      (gemini-3.5-flash-lite)

Model Output:
    - products:
        - product_name
        - category
        - bbox
        - confidence
    - category_summary
"""

import os
import json
from pathlib import Path
from PIL import Image
from time import sleep
from google import genai
from google.genai import types

from dotenv import load_dotenv
# ============================================
# PROMPT AND SCHEMA
# ============================================
PRODUCT_PROMPT = """
You are an expert retail shelf analysis system.

The image contains only ONE shelf region.

Detect every visible product.

Rules:

- Detect every individual product instance.
- Even if multiple identical products exist, output each separately.
- Use the most specific product name you can infer.
- Also provide the generic category.
- Return a normalized bounding box in the format:

[ymin, xmin, ymax, xmax]

where every coordinate is between 0 and 1000.

Bounding boxes should tightly surround the visible product.

Return JSON only.
"""

PRODUCT_SCHEMA = {
    "type": "OBJECT",
    "required": [
        "products",
        "category_summary"
    ],
    "properties": {

        "products": {
            "type": "ARRAY",
            "items": {
                "type": "OBJECT",
                "required": [
                    "product_name",
                    "category",
                    "bbox"
                ],
                "properties": {

                    "product_name": {
                        "type": "STRING"
                    },

                    "category": {
                        "type": "STRING"
                    },

                    "bbox": {
                        "type": "ARRAY",
                        "minItems": 4,
                        "maxItems": 4,
                        "items": {
                            "type": "INTEGER"
                        }
                    },

                    "confidence": {
                        "type": "NUMBER"
                    }
                }
            }
        },

        "category_summary": {
            "type": "ARRAY",
            "items": {
                "type": "OBJECT",
                "properties": {

                    "category": {
                        "type": "STRING"
                    },

                    "count": {
                        "type": "INTEGER"
                    }

                }
            }
        }

    }
}


# ============================================
# CONFIG
# ============================================
VIDEO_NAME = Path("config.txt").read_text(encoding="utf-8").strip()
INPUT_ROOT = fr"masked_shelves\{VIDEO_NAME}"
OUTPUT_ROOT = "product_detection_results"

os.makedirs(OUTPUT_ROOT, exist_ok=True)

load_dotenv()

# ============================================
# GEMINI
# ============================================

client = genai.Client(api_key=os.getenv("API_KEY_PRODUCT_DETECTION"))


def analyze_products(image_path):

    with Image.open(image_path) as image:

        response = client.models.generate_content(

            model="gemini-3.5-flash-lite",

            contents=[
                PRODUCT_PROMPT,
                image
            ],

            config=types.GenerateContentConfig(

                temperature=0,

                response_mime_type="application/json",

                response_schema=PRODUCT_SCHEMA

            )

        )

    return json.loads(response.text)


# =====================================================
# MAIN
# =====================================================

input_folder_name = os.path.basename(os.path.normpath(INPUT_ROOT))

output_video_folder = os.path.join(
    OUTPUT_ROOT,
    input_folder_name
)

os.makedirs(output_video_folder, exist_ok=True)


frame_dirs = sorted([
    d for d in os.listdir(INPUT_ROOT)
    if os.path.isdir(os.path.join(INPUT_ROOT, d))
])


for frame_name in frame_dirs:

    frame_dir = os.path.join(INPUT_ROOT, frame_name)

    save_dir = os.path.join(
        output_video_folder,
        frame_name
    )

    os.makedirs(save_dir, exist_ok=True)

    print(f"\nProcessing frame: {frame_name}")

    shelf_images = sorted([
        f for f in os.listdir(frame_dir)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ])

    for image_name in shelf_images:

        image_path = os.path.join(frame_dir, image_name)

        shelf_id = int(
            os.path.splitext(image_name)[0].split("_")[-1]
        )

        print(f"   Shelf {shelf_id}")

        sleep(5)

        result = analyze_products(image_path)

        result["shelf_id"] = shelf_id

        json_path = os.path.join(
            save_dir,
            f"shelf_{shelf_id}.json"
        )

        with open(json_path, "w", encoding="utf-8") as f:

            json.dump(
                result,
                f,
                indent=4,
                ensure_ascii=False
            )

print("\nDone.")