"""
File:
    Shelf Region Mask Generator

Purpose:
    This script applies polygon-based masks to shelf regions previously detected
    by the detect_shelves module. The generated masked shelf images are used as
    input for the product detection model (detect_products) so that the model
    focuses only on the shelf regions, reducing background distractions and
    improving product detection performance.

Input:
    - A folder containing:
        - Original images
        - Corresponding JSON files generated by detect_shelves
          (one JSON file per image)

Output:
    - A directory containing masked images.
    - For each input image, one masked image is created for every detected
      shelf region.

Main Functionality:
    - Reads the original image and its corresponding shelf annotations.
    - Converts normalized polygon coordinates into image pixel coordinates.
    - Creates a binary mask for each detected shelf region.
    - Applies the mask to keep only the shelf area while removing the
      surrounding scene.
    - Saves each masked shelf region as a separate image.

Workflow:
    detect_shelves
            ↓
    Shelf region polygons (JSON)
            ↓
    Shelf masking (this script)
            ↓
    Masked shelf images
            ↓
    detect_products

"""

import os
import json
from pathlib import Path
import cv2
import numpy as np

def polygon_to_pixels(polygon, width, height):
    pts = []

    for point in polygon:
        y, x = point

        px = int(x / 1000 * width)
        py = int(y / 1000 * height)

        pts.append((px, py))

    return np.array(pts, dtype=np.int32)


def create_masked_shelf_images(image_path, json_path, output_root):

    image = cv2.imread(image_path)

    if image is None:
        print(f"Cannot read image: {image_path}")
        return

    h, w = image.shape[:2]

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    frame_name = os.path.splitext(os.path.basename(image_path))[0]

    save_dir = os.path.join(output_root, frame_name)
    os.makedirs(save_dir, exist_ok=True)

    for shelf in data["shelf_regions"]:

        region_id = shelf["region_id"]

        polygon = polygon_to_pixels(shelf["polygon"], w, h)

        # Siyah maske
        mask = np.zeros((h, w), dtype=np.uint8)

        # Shelf alanını beyaz yap
        cv2.fillPoly(mask, [polygon], 255)

        # Maskeyi uygula
        masked = cv2.bitwise_and(image, image, mask=mask)

        save_path = os.path.join(
            save_dir,
            f"shelf_{region_id}.jpg"
        )

        cv2.imwrite(save_path, masked)

    print(f"Processed {frame_name}")


def process_folder(folder_path, output_root="masked_shelves"):

    folder_name = os.path.basename(os.path.normpath(folder_path))

    output_folder = os.path.join(output_root, folder_name)
    os.makedirs(output_folder, exist_ok=True)

    image_extensions = (".jpg", ".jpeg", ".png")

    images = sorted(
        [
            f for f in os.listdir(folder_path)
            if f.lower().endswith(image_extensions)
        ]
    )

    for image_file in images:

        image_path = os.path.join(folder_path, image_file)

        json_path = os.path.splitext(image_path)[0] + ".json"

        if not os.path.exists(json_path):
            print(f"JSON not found for {image_file}, skipping.")
            continue

        create_masked_shelf_images(
            image_path,
            json_path,
            output_folder
        )


if __name__ == "__main__":

    VIDEO_NAME = Path("config.txt").read_text(encoding="utf-8").strip()
    INPUT_FOLDER = fr"shelf_detection_results\{VIDEO_NAME}"

    process_folder(INPUT_FOLDER)